name: prisma_access_initial_panorama_config

label: Deploy - Step 2 - Prisma Access Panorama Initial Setup

description: |
  License Panorama and update to current POC recommended version.
  Install content updates and the Cloudservice Plugin.

type: docker

labels:
  order: 10
  help_link_title: Prisma Access Panorama Initial Setup
  help_link: https://github.com/PaloAltoNetworks/prisma-access-skillets/tree/master#step-2---initial-panorama-setup
  collection:
    - Prisma Access Deploy Panorama

variables:
  - name: panorama_ip_address
    description: Panorama Public IP Address
    default: 10.10.10.10
    type_hint: ip_address
  - name: adminUsername
    description: Panorama Username
    default: admin
    type_hint: text
  - name: adminPassword
    description: Panorama Password
    default: admin
    type_hint: password
  - name: serial_number
    description: Panorama Serial Number
    default: 000
    type_hint: text
  - name: deployment_type
    description: AWS or Azure Deployment Type
    default: azure
    type_hint: hidden
  - name: private_key_path
    description: path to private key
    default: /home/cnc_user/aws_deploy_key
    type_hint: hidden

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: ansible_test
    image: registry.gitlab.com/panw-gse/as/panos_skillet_tools:latest 
    async: True
    cmd: |
      ansible-playbook -i 'panorama-1,' panorama_initial_config.yml
